aws ec2 describe-tags --filters "Name=tag:Name,Values=CRBS*"
aws rds describe-db-instances --db-instance-identifier "$CRBS_rds_instance_id" --query 'DBInstances[*].[DBInstanceIdentifier][*]'
aws elbv2 describe-load-balancers --load-balancer-arn "$ex_lb_arn"
aws elbv2 describe-load-balancers --load-balancer-arn "$in_lb_arn"
aws elbv2 describe-target-groups --target-group-arns "$UI_tg1"
aws elbv2 describe-target-groups --target-group-arns "$API_tg1"
aws elbv2 describe-target-groups --target-group-arns "$UI_tg2"
aws elbv2 describe-target-groups --target-group-arns "$API_tg2"
aws deploy get-application --application-name "$aws_codedeploy_app"
aws deploy get-deployment-group --application-name "$aws_codedeploy_app" --deployment-group-name "$dg_UI1"
aws deploy get-deployment-group --application-name "$aws_codedeploy_app" --deployment-group-name "$dg_API1"
aws deploy get-deployment-group --application-name "$aws_codedeploy_app" --deployment-group-name "$dg_UI2"
aws deploy get-deployment-group --application-name "$aws_codedeploy_app" --deployment-group-name "$dg_API2"
aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name "$UI_asg1"
aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name "$API_asg1"
aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name "$UI_asg2"
aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name "$API_asg2"
